# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' PRIM Peel
#'
#' This function iteratively peels away a small portion of the matrix M
#' such that the mean of the remaining values in y is maximized.
#'
#' @param M The data to peel away from
#' @param y The labels to evaluate peels
#' @param colTypes Indicates which columns are numeric (0) and which are categorical (1)
#' @param alpha The peeling quantile
#' @param minSup The minimum allowed size of the remainder after a peel
#' @param parallel Peel columns in parallel, faster for many columns (defaults to true)
#' @return A list of peeling steps
#' @author Jurian Baas
#' @export
peel <- function(M, y, colTypes, alpha, minSup, parallel = TRUE) {
    .Call('_subgroup_discovery_peel', PACKAGE = 'subgroup.discovery', M, y, colTypes, alpha, minSup, parallel)
}

#' PRIM Validate
#'
#' This function iteratively goes through the steps from the peeling process
#' and removes any trailing peels which do not improve the overall quality.
#'
#' @param peelSteps Peeling result from calling peel()
#' @param M The data to peel away from
#' @param y The labels to evaluate peels
#' @return A list of peeling steps
#' @author Jurian Baas
#' @export
validate <- function(peelSteps, M, y) {
    .Call('_subgroup_discovery_validate', PACKAGE = 'subgroup.discovery', peelSteps, M, y)
}

