# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

peelCpp <- function(M, y, colTypes, alpha, minSup) {
    .Call(`_subgroup_discovery_peelCpp`, M, y, colTypes, alpha, minSup)
}

predictCpp <- function(peelResult, M, y) {
    .Call(`_subgroup_discovery_predictCpp`, peelResult, M, y)
}

simplifyCpp <- function(peelSteps, colTypes, boxId) {
    .Call(`_subgroup_discovery_simplifyCpp`, peelSteps, colTypes, boxId)
}

indexCpp <- function(boxes, M, boxId) {
    .Call(`_subgroup_discovery_indexCpp`, boxes, M, boxId)
}

